spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/securityft
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=
app.jwt.expirationMs=172800000
spring.jpa.show-sql=true
